### PR TITLE
My html assignment1

### PR DESCRIPTION
**Pull request by RuthO1**
This assignment is about learning how to code a  webpage using HTML and CSS.

### CODE REVIEW

**Comment by burrowdown** [comment]
Nice work!

**Comment by RuthO1** [comment]
Hi Danny. 

Does this mean I can merge? 
Live class was great only that zoom kept crashing from my end.

Meanwhile the white line in my HTML assignment1 header  is a bother-bottom  of 2px solid white. And the margin of my h2 is zero. Check my CSS for #main-title, h1, h2

RuthO

**Comment by RuthO1** [comment]
Hello IBT,


Please I would love to know if the meeting ID for Fullstack software engineering zoom meeting was changed? As I am still unable to join meeting due to invalid meeting ID error.

Regards…
RuthO 

Sent from my iPhone

**Comment by Adesoji1** [comment]
Dear Ruth, it's still the same ID :
https://zoom.us/j/97632680125?pwd=IsfBVEBbGbbUf4uc5uWStrrVHibvnI.1 kindly
verify you have a stable internet connection

**Comment by RuthO1** [comment]
Okay, thank you.

**Pull request merged**
